name: PUBLISH PACKAGE
on:
  release:
    types: [created]
jobs:
  build:
    name: BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Getting Code
        uses: actions/checkout@v2
      - name: Setting Up Nodejs for npm.com
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.com/'
      - name: Installing packages
        run: npm install
  test:
    name: TEST
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Running tests
        run: npm test
  publish:
    name: PUBLISH
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Publishing package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
